version: '3'
services:
  nginx:
    build:
      context: ./nnet-nginx/
    restart: always
    image: seansin/nnet-nginx:latest
    depends_on:
      - app
    volumes:
<<<<<<< HEAD
      - app:/var/www/html/zbxe:rw
      - /d/data/backup:/var/www/html/zbxe/files:rw
=======
      - app:/var/www/html/zbxe:rw 
      - //d/data/backup/attach:/var/www/html/zbxe/files/attach:rw
      - //d/data/backup/site_design:/var/www/html/zbxe/files/site_design
      - //d/data/backup/cache:/var/www/html/zbxe/files/cache
      - //d/data/backup/cache1:/var/www/html/zbxe/files/cache1
      - //d/data/backup/cache2:/var/www/html/zbxe/files/cache2
      - //d/data/backup/thumbnails:/var/www/html/zbxe/files/thumbnails:rw
>>>>>>> f18b885c72b6ea5741468338b01ce1b4aaf24735
      - php:/var/run/php
      - log:/var/log/php
    network_mode: "bridge"
    ports:
      - 80:80
  app:
    build:
      context: ./nnet-app-php7/
    restart: always
    image: seansin/nnet-app-php7:latest
    environment:
      - XE_DBCONFIG_FILE=${XE_DBCONFIG_FILE}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
<<<<<<< HEAD
      - app:/var/www/html/zbxe:rw
      - /d/data/backup:/var/www/html/zbxe/files:rw
      - php:/var/run/php
      - log:/var/log/php 
=======
      - app:/var/www/html/zbxe:rw 
      - //d/data/backup/attach:/var/www/html/zbxe/files/attach:rw
      - //d/data/backup/site_design:/var/www/html/zbxe/files/site_design
      - //d/data/backup/cache:/var/www/html/zbxe/files/cache 
      - //d/data/backup/cache1:/var/www/html/zbxe/files/cache1
      - //d/data/backup/cache2:/var/www/html/zbxe/files/cache2
      - //d/data/backup/thumbnails:/var/www/html/zbxe/files/thumbnails:rw
      - php:/var/run/php
      - log:/var/log/php
>>>>>>> f18b885c72b6ea5741468338b01ce1b4aaf24735
volumes:
  app:
  php: 
  log: