version: '3'
services:
  nginx:
    build:
      context: ./nnet-nginx/
    restart: always
    image: seansin/nnet-nginx:latest
    depends_on:
      - app
    volumes:
      - app:/var/www/html/zbxe:rw
      - /d/data/backup:/var/www/html/zbxe/files:rw
      - php:/var/run/php
      - log:/var/log/php
    network_mode: "bridge"
    ports:
      - 80:80
  app:
    build:
      context: ./nnet-app-php7/
    restart: always
    image: seansin/nnet-app-php7:latest
    environment:
      - XE_DBCONFIG_FILE=${XE_DBCONFIG_FILE}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    volumes:
      - app:/var/www/html/zbxe:rw
      - /d/data/backup:/var/www/html/zbxe/files:rw
      - php:/var/run/php
      - log:/var/log/php 
volumes:
  app:
  php: 
  log: